//! # D-Bus interface proxy for: `org.shadowblip.Input.Debug`
//!
//! This code was generated by `zbus-xmlgen` `6.0.0` from D-Bus introspection data.
//! Source: `org.shadowblip.Input.Debug.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.shadowblip.Input.Debug", assume_defaults = true)]
pub trait Debug {
    /// InputReport signal
    #[zbus(signal)]
    fn input_report(&self) -> zbus::Result<()>;

    /// InputCapabilityReport property
    #[zbus(property)]
    fn input_capability_report(&self) -> zbus::Result<String>;
}
