//! # D-Bus interface proxy for: `org.shadowblip.Input.Source.EventDevice`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `org.shadowblip.Input.Source.EventDevice.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.shadowblip.Input.Source.EventDevice",
    assume_defaults = true
)]
pub trait EventDevice {
    /// DeviceClass property
    #[zbus(property)]
    fn device_class(&self) -> zbus::Result<String>;

    /// DevicePath property
    #[zbus(property)]
    fn device_path(&self) -> zbus::Result<String>;

    /// IdBustype property
    #[zbus(property)]
    fn id_bustype(&self) -> zbus::Result<String>;

    /// IdProduct property
    #[zbus(property)]
    fn id_product(&self) -> zbus::Result<String>;

    /// IdVendor property
    #[zbus(property)]
    fn id_vendor(&self) -> zbus::Result<String>;

    /// IdVersion property
    #[zbus(property)]
    fn id_version(&self) -> zbus::Result<String>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// PhysPath property
    #[zbus(property)]
    fn phys_path(&self) -> zbus::Result<String>;

    /// SupportedAbsoluteAxes property
    #[zbus(property)]
    fn supported_absolute_axes(&self) -> zbus::Result<Vec<u16>>;

    /// SupportedFf property
    #[zbus(property)]
    fn supported_ff(&self) -> zbus::Result<Vec<u16>>;

    /// SupportedKeys property
    #[zbus(property)]
    fn supported_keys(&self) -> zbus::Result<Vec<u16>>;

    /// SupportedLeds property
    #[zbus(property)]
    fn supported_leds(&self) -> zbus::Result<Vec<u16>>;

    /// SupportedRelativeAxes property
    #[zbus(property)]
    fn supported_relative_axes(&self) -> zbus::Result<Vec<u16>>;

    /// SupportedSounds property
    #[zbus(property)]
    fn supported_sounds(&self) -> zbus::Result<Vec<u16>>;

    /// SupportedSwitches property
    #[zbus(property)]
    fn supported_switches(&self) -> zbus::Result<Vec<u16>>;

    /// SysfsPath property
    #[zbus(property)]
    fn sysfs_path(&self) -> zbus::Result<String>;

    /// UniqueId property
    #[zbus(property)]
    fn unique_id(&self) -> zbus::Result<String>;
}
