//! # D-Bus interface proxy for: `org.shadowblip.Input.Source.IIOIMUDevice`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `org.shadowblip.Input.Source.IIOIMUDevice.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.shadowblip.Input.Source.IIOIMUDevice",
    assume_defaults = true
)]
pub trait IIOIMUDevice {
    /// AccelSampleRate property
    #[zbus(property)]
    fn accel_sample_rate(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_accel_sample_rate(&self, value: &str) -> zbus::Result<()>;

    /// AccelSampleRatesAvail property
    #[zbus(property)]
    fn accel_sample_rates_avail(&self) -> zbus::Result<String>;

    /// AccelScale property
    #[zbus(property)]
    fn accel_scale(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_accel_scale(&self, value: &str) -> zbus::Result<()>;

    /// AccelScalesAvail property
    #[zbus(property)]
    fn accel_scales_avail(&self) -> zbus::Result<String>;

    /// AngvelSampleRate property
    #[zbus(property)]
    fn angvel_sample_rate(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_angvel_sample_rate(&self, value: &str) -> zbus::Result<()>;

    /// AngvelSampleRatesAvail property
    #[zbus(property)]
    fn angvel_sample_rates_avail(&self) -> zbus::Result<String>;

    /// AngvelScale property
    #[zbus(property)]
    fn angvel_scale(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_angvel_scale(&self, value: &str) -> zbus::Result<()>;

    /// AngvelScalesAvail property
    #[zbus(property)]
    fn angvel_scales_avail(&self) -> zbus::Result<String>;

    /// Id property
    #[zbus(property)]
    fn id(&self) -> zbus::Result<String>;
}
