//! # D-Bus interface proxy for: `org.shadowblip.Input.Source.UdevDevice`
//!
//! This code was generated by `zbus-xmlgen` `6.0.0` from D-Bus introspection data.
//! Source: `org.shadowblip.Input.UdevDevice.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.shadowblip.Input.Source.UdevDevice",
    assume_defaults = true
)]
pub trait UdevDevice {
    /// DevicePath property
    #[zbus(property)]
    fn device_path(&self) -> zbus::Result<String>;

    /// IdBustype property
    #[zbus(property)]
    fn id_bustype(&self) -> zbus::Result<String>;

    /// IdProduct property
    #[zbus(property)]
    fn id_product(&self) -> zbus::Result<String>;

    /// IdVendor property
    #[zbus(property)]
    fn id_vendor(&self) -> zbus::Result<String>;

    /// IdVersion property
    #[zbus(property)]
    fn id_version(&self) -> zbus::Result<String>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// PhysPath property
    #[zbus(property)]
    fn phys_path(&self) -> zbus::Result<String>;

    /// Properties property
    #[zbus(property)]
    fn properties(&self) -> zbus::Result<std::collections::HashMap<String, String>>;

    /// Subsystem property
    #[zbus(property)]
    fn subsystem(&self) -> zbus::Result<String>;

    /// SysfsPath property
    #[zbus(property)]
    fn sysfs_path(&self) -> zbus::Result<String>;

    /// UniqueId property
    #[zbus(property)]
    fn unique_id(&self) -> zbus::Result<String>;
}
